on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: CPU Model
        run: cat /proc/cpuinfo  | grep 'name'| uniq
      - name: CPU Cores
        run: cat /proc/cpuinfo  | grep process| wc -l
      - name: Disk Space
        run: df -h
      - name: RAM MB
        run: free --mega
      - name: Clone Unreal Engine 5
        run: |
          git config --global user.email xavisolesoft@gmail.com 
          git config --global user.name xavisolesoft
          git config --global url.https://${{ secrets.PAT }}@github.com/.insteadOf https://github.com/
      - name: LS
        run: ls -la
