on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: CPU Model
        run: cat /proc/cpuinfo  | grep 'name'| uniq
      - name: CPU Cores
        run: cat /proc/cpuinfo  | grep process| wc -l
      - name: Disk Space
        run: df -h
      - name: RAM MB
        run: free --mega
      - name: Build CARLA
        run: git config --global user.name xavisolesoft && git config --global user.password ${{ secrets.GITHUB_TOKEN }} && git clone -b ue5-dev https://github.com/carla-simulator/carla.git CarlaUE5 && cd CarlaUE5 && bash -x Setup.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
