on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: CPU Model
        run: cat /proc/cpuinfo  | grep 'name'| uniq
      - name: CPU Cores
        run: cat /proc/cpuinfo  | grep process| wc -l
      - name: Disk Space
        run: df -h
      - name: RAM MB
        run: free --mega
      - name: Clone Unreal Engine 5
        run: git clone --depth=1 -b ue5-dev-carla https://github.com/CarlaUnreal/UnrealEngine.git UnrealEngine5_carla_test
      - name: LS
        run: ls -la
