on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: CPU Model
        run: cat /proc/cpuinfo  | grep 'name'| uniq
      - name: CPU Cores
        run: cat /proc/cpuinfo  | grep process| wc -l
      - name: Disk Space
        run: df -h
      - name: RAM MB
        run: free --mega
      - uses: actions/checkout@v3  # v3 is the latest version
        with:
          repository: xavisolesoft/TestActions
      - name: PWD
        run: pwd
